[tool.poetry]
name = "django-amplitude"
packages = [
    {include = "amplitude"}
]
version = "0.7.1"
description = "Integration between Django and Amplitude"
authors = ["Matt Pye <pyematt@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/pyepye/django-amplitude"
homepage = "https://github.com/pyepye/django-amplitude"
keywords = ["amplitude", "analytics", "product analytics", "saas"]


[tool.poetry.dependencies]
python = "^3.7"
Django = ">=2.1"
httpx = ">=0.13.2"
user-agents = "^2.1"


[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.1.0"
pytest-django = "^4.5.2"
pytest-freezegun = "^0.4.1"
flake8 = "^4.0.1"
tox = "^3.25.0"
django-stubs = "^1.5.0"
isort = {extras = ["pyproject"], version = "^5.11.4"}


[tool.isort]
line_length = 79
multi_line_output = 5
known_third_party = "pytest"
known_first_party = "amplitude"
skip_glob = "__pycache__/*,venv/*,.venv/*,.tox/*,.mypy_cache"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
